Update README.md
Anima-Tec/2021_Proyecto_Integrador_Equipo_3-Backend pull request #14
Opened 2021-09-11 15:30 UTC by alejandroGonGon

2021-09-14 01:15 UTC, nicocadq requested changes

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +usar/actualizar migrations
es necesario el `migrate:fresh`?

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +usar/actualizar migrations
```suggestion
correr las migraciones de nuestra base de datos
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +Para correr el proyecto usar :
```suggestion
Levantar el servidor :
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +## Variables de entorno
Pondria la secion de `Variables de entorno` antes que la de `Levantando el servicio`, ya que son necesaria para poder levantarlo.

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +Para poder correr el proyecto correctamente se necesita cambiar algunas variables de entorno, tales como :
```suggestion
Para poder levantar el servicio correctamente se necesitan ciertas variables de entorno :
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +Estas siendo para configurar donde se localizara la base de datos.
```suggestion
Informacion sobre nuestra base de datos local.
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +`DB_PASSWORD`
Faltan mencionar varias variables de entorno, como la de los mails o las de mailtrap

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +
No es necesario volver a nombrarlo, ya lo explicas arriba

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +A continuación se explicará todo sobre la creación de los Endpoints realizados y su formato dentro de la herramienta seleccionada [Postman](https://www.postman.com/).
```suggestion
Encontraran una coleccion de [Postman](https://www.postman.com/) con todos los endpoints de nuestra aplicacion.
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +### Collection
```suggestion
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +
```suggestion
La autentificacion de la aplicacion esta basada en tokens y la seguridad en rutas dependientes de la presencia de estos tokens. Para una correcta gestion de la autentificacion utilizamos [Sanctum](https://laravel.com/docs/8.x/sanctum#how-it-works).

Decidimos utilizar este metodo ya que se amolda a las necesidades del proyecto, ademas tiene cierta sencilles en su implementacion lo que agilizo el proceso de desarrollo.

```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +_Ejemplo de la protección vía Sanctum :_
```suggestion
Las rutas que necesitan autentificacion estas agrupadas bajo el `middleware` de Sanctum dentro de nuestro archivo de rutas.
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +    // Todas las rutas puestas aqui estarán protegidas y solo serán ejecutadas si la autenticación via token coincide.
```suggestion
    // Todas las rutas puestas aqui estarán protegidas y solo podran ser accedidas si la autenticación via token es exitosa.
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +```
```suggestion
Las rutas que esten por fuera del `middleware` no tendran autentificacion.
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +Para la creacion de los endpoints dentro del proyecto, se utilizo la herramienta ya mencionada anteriormente, Postman.
```suggestion
Para la creacion de los endpoints dentro del proyecto, se utilizo la herramienta ya mencionada anteriormente, Postman.
```
```suggestion

```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +Aclarar que el limite de objetos recibidos a mostrar dentro de una Request es de 10, siendo lo suficientemente neccesario para el uso dentro del FrontEnd.
Hemos utilizado las facilidades que nos da Eloquent para poder paginar los endpoints de nuestra API que devuelven grandes cantidades de recursos. Decidimos que el limite de registros enviados en un endpoint paginado seria de 10, un limite que del lado del cliente es aceptable.

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +### EJemplo de una Request con Pagination :
```suggestion
### Ejemplo de una endpoint con paginacion :
```

2021-09-14 01:15 UTC, nicocadq commented on README.md
> +## Request
```suggestion
## Paginacion en los endpoints
```

2021-09-14 17:23 UTC, alejandroGonGon commented on README.md
> +## Variables de entorno
Me parece una buena observacion.

2021-09-14 17:25 UTC, alejandroGonGon commented on README.md
> +`DB_PASSWORD`
Estas seran remplazadas por el servicio que levantara facu de mails en un futuro, si esto no llegase a pasar, si se explicara el manejo de estas variables.

2021-09-14 17:27 UTC, alejandroGonGon commented on README.md
> +
Me parecia bueno volver a traer el tema pero mas a fondo.

2021-09-14 17:29 UTC, alejandroGonGon commented on README.md
> +### Collection
Me parece que collections son neccesarias como titulo para explicar lo de Postaman

2021-09-14 17:31 UTC, alejandroGonGon commented on README.md
> +Aclarar que el limite de objetos recibidos a mostrar dentro de una Request es de 10, siendo lo suficientemente neccesario para el uso dentro del FrontEnd.
Me parece bien.

2021-09-15 15:13 UTC, nicocadq approved these changes

2021-09-15 19:01 UTC, merged