agregando atributos a un user y  haciendo el endpoint de update a user
Anima-Tec/2021_Proyecto_Integrador_Equipo_3-Backend pull request #15
Opened 2021-09-13 14:33 UTC by alejandroGonGon

2021-09-14 00:48 UTC, nicocadq requested changes

2021-09-14 00:48 UTC, nicocadq commented on routes/api.php
> +    Route::put('/update/{id}', [AuthController::class, 'update']);
No es necesario poner la accion en la URI, podemos inferirlo con el metodo HTTP el cual espera la ruta (PUT...para editar recursos)

```suggestion
    Route::put('/{id}', [AuthController::class, 'update']);
```

2021-09-14 00:48 UTC, nicocadq commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('phone')->default('+598');
No me parece lo mas apropiado agregar estos campos por default (mucho menos agregarlo en ingles)

2021-09-14 00:48 UTC, nicocadq commented on app/Http/Controllers/AuthController.php
> +    public function update(Request $request, $id)
Deberiamos validar los campos `request`?

2021-09-14 17:33 UTC, alejandroGonGon commented on routes/api.php
> +    Route::put('/update/{id}', [AuthController::class, 'update']);
A mi me parece que es simple de leerlo y comprenderlo, porque al fin y al cabo PUT y UPDATE son conceptos que van a lo mismo pero no esta de mas aclaralo, para asi alguien que no este afin con el codigo pueda comprenderlo.

¿ Que decis ?

2021-09-14 17:34 UTC, alejandroGonGon commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('phone')->default('+598');
Al momento de la creacion de estos dentro de la llamda por el Endpoint me pedia que usase un default.

2021-09-14 17:36 UTC, alejandroGonGon commented on app/Http/Controllers/AuthController.php
> +    public function update(Request $request, $id)
No entendi a lo que referis, podrias volver a explicarlo de otra forma.

2021-09-14 19:23 UTC, nicocadq commented on routes/api.php
> +    Route::put('/update/{id}', [AuthController::class, 'update']);
Creo que es sobre explicar, lo cual no hace que nuestra interfaz luzca de calidad.

2021-09-14 19:29 UTC, nicocadq commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('phone')->default('+598');
Podes marcarlos com `nullable` en el schema.
```
table->atributo('nombre')->nullable();
```
Por otro lado, creo que el campo `about_me` y la descripcion de una donacion deberian ser `longText` en vez de solo text.

2021-09-14 19:32 UTC, nicocadq commented on app/Http/Controllers/AuthController.php
> +    public function update(Request $request, $id)
Seguro, en la funcion `update` estas reciviendo el atributo `$request` el cual asumo que contiene los valores que a vas a cambiar dentro del recurso (User). Estos valores vienen desde un lugar externo, deberiamos chequear que tengas los valores correctos? Es decir, que sean los campos deseados, que esten en el tipo de dato deseado, que no se hayan eliminado atributos requeridos.

2021-09-15 15:10 UTC, nicocadq approved these changes

2021-09-29 00:26 UTC, nicocadq approved these changes

2021-09-29 00:26 UTC, nicocadq commented on app/Http/Controllers/AuthController.php
> +        'phone' => 'integer',
I think that it should be a string

2021-09-29 00:26 UTC, nicocadq commented on app/Http/Controllers/AuthController.php
> +    $user->update($fields);
It could be a better choice to use the `findAndUpdate`

2021-09-29 00:26 UTC, nicocadq commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('phone')->nullable();
`image` has to be a string because you cant add the `+` later, and also if there is a `093418251` it would be `93418251` in the database

2021-09-29 00:26 UTC, nicocadq commented on routes/api.php
> +    Route::put('/users/{id}', [AuthController::class, 'update']);
try to group your routes by an entity, I mean if you have donation related routes try to put it together

2021-09-29 13:16 UTC, alejandroGonGon commented on app/Http/Controllers/AuthController.php
> +    $user->update($fields);
No existe eso.

2021-09-29 13:18 UTC, alejandroGonGon commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->integer('phone')->nullable();
Done

2021-10-01 11:27 UTC, nicocadq approved these changes
Good stuff, merge it before solve the comments 🤙🏻

2021-10-01 11:27 UTC, nicocadq commented on app/Http/Controllers/AuthController.php
> +    $user = User::find($id);
Update the image attached to the user

2021-10-01 11:52 UTC, alejandroGonGon commented on app/Http/Controllers/AuthController.php
> +    $user = User::find($id);
Done in last commit

2021-10-01 11:52 UTC, merged